


TABLE_NAME_SNP_ANNOTATION = "snp_annotation"
TABLE_NAME_REFERENCES = "snp_references"
TABLE_NAME_NODES = "nodes"
TABLE_NAME_TREE = "tree"

SNP_COLUMN_NODE_ID,		SNP_COLUMN_NODE_ID_TYPE		 = "node_id",			("INTEGER",)
SNP_COLUMN_SNP_ID,		SNP_COLUMN_SNP_ID_TYPE		 = "snp_id",			("VARCHAR(6)", "PRIMARY KEY")
SNP_COLUMN_POSITION,	SNP_COLUMN_POSITION_TYPE	 = "position",			("INTEGER",)
SNP_COLUMN_ANCESTRAL,	SNP_COLUMN_ANCESTRAL_TYPE	 = "ancestral_base",	("VARCHAR(1)",)
SNP_COLUMN_DERIVED,		SNP_COLUMN_DERIVED_TYPE		 = "derived_base",		("VARCHAR(1)",)
SNP_COLUMN_REFERENCE,	SNP_COLUMN_REFERENCE_TYPE	 = "reference",			("VARCHAR(20)",)
SNP_COLUMN_DATE,		SNP_COLUMN_DATE_TYPE		 = "date",				("DATETIME",)
SNP_COLUMN_GENOME_ID,	SNP_COLUMN_GENOME_ID_TYPE	 = "genome_i",			("INTEGER",)

REFERENCE_COLUMN_GENOME_ID,	REFERENCE_COLUMN_GENOME_ID_TYPE    = "id",				("",)
REFERENCE_COLUMN_GENOME,	REFERENCE_COLUMN_GENOME_TYPE       = "genome",			("",)
REFERENCE_COLUMN_STRAIN,	REFERENCE_COLUMN_STRAIN_TYPE       = "strain",			("",)
REFERENCE_COLUMN_GENBANK,	REFERENCE_COLUMN_GENBANK_TYPE      = "genbank_id",		("",)
REFERENCE_COLUMN_REFSEQ,	REFERENCE_COLUMN_REFSEQ_TYPE       = "refseq_id",		("",)
REFERENCE_COLUMN_ASSEMBLY,	REFERENCE_COLUMN_ASSEMBLY_TYPE     = "assembly_name",	("",)

NODE_COLUMN_ID,		NODE_COLUMN_ID_TYPE		= "id",		("",)
NODE_COLUMN_NAME,	NODE_COLUMN_NAME_TYPE	= "name",	("",)

TREE_COLUMN_PARENT,	TREE_COLUMN_PARENT_TYPE	= "parent",	("",)
TREE_COLUMN_CHILD,	TREE_COLUMN_CHILD_TYPE	= "child",	("",)
TREE_COLUMN_RANK,	TREE_COLUMN_RANK_TYPE	= "rank_i",	("",)